packageExtensions:
  "react-simple-animate@*":
    dependencies:
      "react": "latest"
  "react-transition-group@*":
    dependencies:
      "react-dom": "latest"
  "jest-config@*":
    dependencies:
      "ts-node": "latest"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
